In [2]:
import numpy as np

In [3]:
print("hello world")

hello world


In [4]:
my_list=[1,2,3,4,5,6]
array=np.array(my_list)

In [5]:
array


array([1, 2, 3, 4, 5, 6])

In [6]:
type(array)

numpy.ndarray

In [7]:
array.shape

(6,)

In [8]:
arr=np.arange(0,10)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
import random

In [13]:
np.random.randn(3,4)

array([[-1.13345914, -0.5846364 ,  0.64078476, -0.25557426],
       [-1.14378617, -0.65221281, -0.24553514,  1.2311025 ],
       [ 0.38944673,  1.55080257,  0.14184005,  1.07108939]])

In [14]:
np.random.rand(3,3)

array([[0.51031181, 0.36821533, 0.46688965],
       [0.5474597 , 0.45015532, 0.70771648],
       [0.90818928, 0.87646385, 0.98574021]])

In [15]:
np.random.random_sample()

0.11285855808778655

In [16]:
import pandas as pd

In [17]:
from io import StringIO,BytesIO


In [21]:
data=('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'



    
)

In [22]:
type(data)

str

In [23]:
pd.read_csv(StringIO(data))

,col1,col2,col3
0,x,y,1
1,a,b,2


In [24]:
StringIO

_io.StringIO